"""update

Revision ID: 17adbff7d646
Revises: 223a60511898
Create Date: 2020-07-01 23:39:53.093081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17adbff7d646'
down_revision = '223a60511898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_series', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bethesda_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_series', schema=None) as batch_op:
        batch_op.drop_column('bethesda_level')

    # ### end Alembic commands ###
