"""init

Revision ID: 223a60511898
Revises: 
Create Date: 2020-07-01 16:55:02.269619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223a60511898'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('image_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_id', sa.String(length=255), nullable=True),
    sa.Column('patient_birth_date', sa.String(length=255), nullable=True),
    sa.Column('patient_sex', sa.String(length=10), nullable=True),
    sa.Column('patient_age', sa.String(length=10), nullable=True),
    sa.Column('patient_weight', sa.String(length=10), nullable=True),
    sa.Column('patient_address', sa.String(), nullable=True),
    sa.Column('patient_comments', sa.String(), nullable=True),
    sa.Column('contour_color', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('contour',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attributes', sa.String(length=512), nullable=True),
    sa.Column('other_attr', sa.String(), nullable=True),
    sa.Column('frame_number', sa.Integer(), nullable=True),
    sa.Column('slice_location', sa.Integer(), nullable=True),
    sa.Column('knot_frames', sa.String(), nullable=True),
    sa.Column('points', sa.String(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['image_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('row_pixel_spacing', sa.Float(), nullable=True),
    sa.Column('column_pixel_spacing', sa.Float(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('frame_idx', sa.Integer(), nullable=True),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['image_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('columns', sa.Integer(), nullable=True),
    sa.Column('row_pixel_spacing', sa.Float(), nullable=True),
    sa.Column('column_pixel_spacing', sa.Float(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['image_series.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slice')
    op.drop_table('image')
    op.drop_table('contour')
    op.drop_table('user')
    op.drop_table('image_series')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
